name: CI

on:
  push:
    branches:
     - 'main'
  pull_request:
  # schedule:
  #    - cron: '15 2 * * 6'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test-docker-image:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Build Docker Image
        id: build-and-push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          context: .
          push: false
          tags: '${{ env.IMAGE_NAME }}:${{ github.sha }}'

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.4.0
      #   with:
      #     image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
      #     format: 'template'
      #     template: '@/contrib/sarif.tpl'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
